version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: api-bd-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api-bd-pg
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
